name: orca_sim
description: "Gerenciador de orçamentos para prestadores de serviço."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Banco de Dados e Auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

  # Utils
  intl: ^0.19.0
  pdf: ^3.10.0
  printing: ^5.11.0
  image_picker: ^1.1.0
  brasil_fields: ^1.15.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# 1. ÍCONE DO APLICATIVO (Menu do celular)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icone_app.png" 
  min_sdk_android: 21 
  # Ícone Adaptativo
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icone_novo.png" # Usa o novo

# 2. TELA DE ABERTURA NATIVA (SplashScreen)
flutter_native_splash:
  color: "#000000"
  # image: assets/icone_novo.png  <-- COMENTE OU APAGUE ESSA LINHA
  # branding: assets/icone_novo.png <-- COMENTE OU APAGUE ESSA LINHA
  
  color_dark: "#000000"
  # image_dark: assets/icone_novo.png <-- COMENTE OU APAGUE ESSA LINHA

  android_12:
    # image: assets/icone_novo.png <-- COMENTE OU APAGUE ESSA LINHA
    color: "#000000"
    icon_background_color: "#000000"

    dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Banco de Dados e Auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

  # Utils
  intl: ^0.19.0
  pdf: ^3.10.0
  printing: ^5.11.0
  image_picker: ^1.1.0
  
  # --- NOVOS PACOTES AQUI ---
  brasil_fields: ^1.15.0  # Para máscaras
  path_provider: ^2.1.2   # Para salvar arquivos locais
  path: ^1.9.0            # Para manipular nomes de arquivos

flutter:
  uses-material-design: true
  assets:
    - assets/